/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCases"];
        put?: never;
        post: operations["createCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{caseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCase"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{caseId}/artifact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{caseId}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{caseId}/bundle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBundle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        StatusResponse: {
            status: string;
        };
        ErrorResponse: {
            code: string;
            message: string;
            details?: {
                [key: string]: string;
            };
        };
        ToolStatus: {
            name: string;
            path?: string;
            version?: string;
            status: string;
        };
        UploadInfo: {
            fileName: string;
            /** Format: int64 */
            sizeBytes: number;
            durationSeconds: number;
            width: number;
            height: number;
            frameRate: number;
            sha256: string;
        };
        CaseSummary: {
            id: string;
            name: string;
            /** @enum {string} */
            status: "queued" | "processing" | "complete" | "failed";
            message: string;
            progress: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            uploads: components["schemas"]["UploadInfo"][];
            artifactUrl?: string;
            reportUrl?: string;
            error?: components["schemas"]["ErrorResponse"];
        };
        CreateCaseResponse: {
            case: components["schemas"]["CaseSummary"];
        };
        Point3D: {
            id: string;
            x: number;
            y: number;
            z: number;
            color: number[];
            tags?: string[];
        };
        CameraPose: {
            id: string;
            sourceVideo: string;
            timeSeconds: number;
            position: components["schemas"]["Vec3"];
            rotationEuler: components["schemas"]["Vec3"];
            focalLengthPx: number;
        };
        VehicleTrackPoint: {
            timeSeconds: number;
            x: number;
            y: number;
            z: number;
            speedMps: number;
        };
        SpeedEstimate: {
            method: string;
            meanMps: number;
            meanKph: number;
            meanMph: number;
            lowerKph: number;
            upperKph: number;
            confidence: number;
            notes: string[];
        };
        ReconstructionQuality: {
            mode: string;
            inputVideos: number;
            coordinateFrame: string;
            toolchain: components["schemas"]["ToolStatus"][];
            warnings: string[];
            reprojectionRmse?: number;
        };
        Artifact: {
            caseId: string;
            caseName: string;
            version: string;
            commit: string;
            /** Format: date-time */
            createdAt: string;
            coordinateFrame: string;
            uploads: components["schemas"]["UploadInfo"][];
            points: components["schemas"]["Point3D"][];
            cameras: components["schemas"]["CameraPose"][];
            vehicleTrack: components["schemas"]["VehicleTrackPoint"][];
            speed: components["schemas"]["SpeedEstimate"];
            quality: components["schemas"]["ReconstructionQuality"];
            reportMarkdown: string;
        };
        Vec3: number[];
    };
    responses: {
        /** @description Structured error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        CaseId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    getReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    listTools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Toolchain status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolStatus"][];
                };
            };
        };
    };
    listCases: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cases held by this backend process */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        cases: components["schemas"]["CaseSummary"][];
                    };
                };
            };
        };
    };
    createCase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    case_name?: string;
                    /** Format: double */
                    scale_meters?: number;
                    videos: string[];
                };
            };
        };
        responses: {
            /** @description Case accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateCaseResponse"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    getCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caseId: components["parameters"]["CaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Case summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseSummary"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    getArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caseId: components["parameters"]["CaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reconstruction artifact */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artifact"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    getReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caseId: components["parameters"]["CaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Markdown report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/markdown": string;
                };
            };
            404: components["responses"]["Error"];
        };
    };
    getBundle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caseId: components["parameters"]["CaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ZIP evidence bundle */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": string;
                };
            };
        };
    };
}
